import React from 'react';
import Head from 'next/head';
import Footer from '../components/Footer';
import Navbar from '../components/Navbar';
import Main from '../components/Main';
import Project from '../components/Project';
import Blog from '../components/Blog';
import Skill from '../components/Skill';

export default function Home() {
  return (
    <div className='p-0'>
      <Head>
        <title>Portfolio Gerrad</title>
        <meta name='description' content='Generated by create next app' />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Headland+One&family=Ibarra+Real+Nova:wght@400;600&display=swap');
        </style>
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <main className='bg-black-2 w-full px-[2.5rem] md:px-[4.5rem] lg:px-[8rem]'>
        <Main />
        <Project />
        <Skill />
        <Blog />
      </main>

      <Footer />
    </div>
  );
}
